### ISSUE TITLE
Questions regarding Uni-Fold multimer evaluation

### ISSUE THREAD

**Issue by SuperXiang** [dptech-corp/Uni-Fold#80]
Thanks for presenting the great work of Uni-Fold on Protein Structure Prediction. I have a few questions regarding the multimer evaluation part.

1. As for multimer evaluation, it's said in the paper that you merge all chains into one before scoring. Do you predict the multimers with all chains and then remove the **TER** symbol in the output pdb files before using the **TMscore/lDDT** tool? Or do you just use the command **$ TMscore -c model.pdb native.pdb** with -**ter <= 1**? Would you share more details or the scripts of the evaluation part since I haven't found it within the GitHub repo?

2. Since the order of different chains might be a problem in the predicted multimers, it's said in the paper that you **iterate over all possible permutation alignments** during evaluation. Would you share any related codes of this part so that I can align my experiment results with yours?

3. I think It's common to use DockQ during the multimer evaluation. May I know any reason for not using this metric besides _leading to confusion_ which is said in the paper?

**Comment by guolinke** [comment]
The code of TM-Score (and other metrics) evaluation is written by our own. We consider the permutation of the chains, and only evaluate the C_\alpha atoms that have labeled coordinates. The script for evaluation is at https://github.com/dptech-corp/Uni-Fold/pull/82

We didn't use DockQ score since it is designed for the dimer. There are many multimers with #chain > 2. Besides, TM-Score can better reflect the overall structure prediction accuracy, while dockQ focuses on the interface.

**Comment by SuperXiang** [comment]
Thanks for the response. I will check it.
